# Report the Best Parameter Sets found in each NNI Experiment

In [1]:
import os
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt

from utils import add_roll_mean, trials_to_goal, get_best, str_to_arr

import warnings
warnings.filterwarnings('ignore')

Get data from pickle or csvs files

In [2]:
data_type = "csvs" #"pickles"

folder = f'.\\data\\nni_{data_type}'

Make a list of the hyperparameters that were tested

In [3]:
params_list = ['n_rotates', 'n_scales', 'length_scale', 'lr', 'act_dis', 'state_dis', 'active_prop', 'eps']

Create a single dataframe containing the parameter sets that achieve the top 5% performance

In [4]:
count=0
for filename in os.listdir(folder):
    filepath = os.path.join(folder, filename)
    
    ## Read the data to a pandas dataframe
    if data_type == "csvs":
        df = pd.read_csv(filepath)
    elif data_type == "pickles":
        df = pd.read_pickle(filepath)
        
    df = str_to_arr(df, ['episodes', 'rewards'])
        
    ## Add the rolling mean rewards as a new column
    df = add_roll_mean(df)
    
    ## Calculate number of trials to goal rolling mean and add it as a new column
    df = trials_to_goal(df, 95)
    
    df_best = get_best(df, params_list)

    ## Only get the columns of interest
    df_best = df_best[['index'] + params_list]

    ## Remove duplicate rows
    df_best.drop_duplicates()

    ## Add exp column
    df_best['exp'] = filename
        
    if count == 0: 
        ## Make new joint df 
        df_best_all = df_best
        
    else: 
        df_best_all = pd.concat([df_best_all, df_best])
        
    count+=1

Show results

In [5]:
df_best_all

,index,n_rotates,n_scales,length_scale,lr,act_dis,state_dis,active_prop,eps,exp
0,0,4,1,1.000000,0.148260,0.815828,0.981973,0.100000,0.383644,ratbox100_discrete10.csv
1,1,4,1,1.000000,0.009559,0.997999,0.978057,0.100000,0.446527,ratbox100_discrete10.csv
2,2,4,1,1.000000,0.003878,0.970027,0.879743,0.100000,0.550991,ratbox100_discrete10.csv
3,3,4,1,1.000000,0.004342,0.827770,0.920651,0.100000,0.346343,ratbox100_discrete10.csv
4,4,4,1,1.000000,0.006811,0.854644,0.828833,0.100000,0.535418,ratbox100_discrete10.csv
0,0,4,1,1.000000,0.343780,0.908315,0.908915,0.100000,0.361120,ratbox100_discrete12.csv
1,1,4,1,1.000000,0.008628,0.961214,0.828801,0.100000,0.401866,ratbox100_discrete12.csv
2,2,4,1,1.000000,0.023758,0.952302,0.849024,0.100000,0.541772,ratbox100_discrete12.csv
3,3,4,1,1.000000,0.003840,0.895973,0.857758,0.100000,0.318860,ratbox100_discrete12.csv
4,4,4,1,1.000000,0.004963,0.971761,0.924515,0.100000,0.513579,ratbox100_discrete12.csv
0,0,4,1,1.000000,0.300605,0.947206,0.966626,0.100000,0.439516,ratbox100_discrete6.csv
1,90,4,1,1.000000,0.297329,0.867190,0.819517,0.100000,0.516749,ratbox100_discrete6.csv
2,21,4,1,1.000000,0.325081,0.829086,0.837764,0.100000,0.505375,ratbox100_discrete6.csv
3,52,4,1,1.000000,0.453211,0.885068,0.830351,0.100000,0.543266,ratbox100_discrete6.csv
4,68,4,1,1.000000,0.326813,0.871565,0.843755,0.100000,0.526007,ratbox100_discrete6.csv
0,28,4,1,1.000000,0.247154,0.949027,0.841157,0.100000,0.580777,ratbox100_discrete8.csv
1,46,4,1,1.000000,0.333143,0.934979,0.835913,0.100000,0.517557,ratbox100_discrete8.csv
2,14,4,1,1.000000,0.166810,0.926754,0.880007,0.100000,0.517200,ratbox100_discrete8.csv
3,21,4,1,1.000000,0.217374,0.952703,0.854658,0.100000,0.540155,ratbox100_discrete8.csv
4,3,4,1,1.000000,0.183290,0.825996,0.805627,0.100000,0.472904,ratbox100_discrete8.csv
0,32,7,9,90.202990,0.290358,0.836601,0.842407,0.284970,0.431268,ratbox100_hexssp.csv
1,33,7,9,81.040428,0.195576,0.816839,0.829762,0.232474,0.438299,ratbox100_hexssp.csv
2,55,7,6,91.775829,0.206206,0.820566,0.857552,0.156189,0.360414,ratbox100_hexssp.csv
3,91,7,9,91.773429,0.307744,0.834214,0.847267,0.288134,0.422046,ratbox100_hexssp.csv
4,59,10,6,94.858256,0.443321,0.823727,0.866109,0.205024,0.374556,ratbox100_hexssp.csv